
library(data.table)
gsub(" ", "", colSatSurvey$Airline.Status, fixed = TRUE)
gsub(" ", "", colSatSurvey$Gender, fixed = TRUE)
trimws(colSatSurvey$Type.of.Travel)
trimws(colSatSurvey$Class)
trimws(colSatSurvey$Airline.Code)
trimws(colSatSurvey$Airline.Name)
trimws(colSatSurvey$Origin.City)
trimws(colSatSurvey$Origin.State)
trimws(colSatSurvey$Destination.City)
trimSatSurvey <- trimws(colSatSurvey$Destination.State)
